using JD.MSBuild.Fluent.IR;
using JD.MSBuild.Fluent.Packaging;
using JD.MSBuild.Fluent.Typed;

namespace JD.MSBuild.Fluent.Fluent;

/// <summary>
/// Entry point for fluent package definition.
/// </summary>
public static class Package
{
  /// <summary>
  /// Starts defining a package with the specified ID.
  /// </summary>
  public static PackageBuilder Define(string id) => new(id);
}

/// <summary>
/// Fluent builder for creating <see cref="PackageDefinition"/> instances.
/// </summary>
public sealed class PackageBuilder
{
  private readonly PackageDefinition _def;

  /// <summary>
  /// Creates a package builder with the given ID.
  /// </summary>
  public PackageBuilder(string id)
  {
    _def = new PackageDefinition { Id = id };
  }

  /// <summary>
  /// Sets the package description.
  /// </summary>
  public PackageBuilder Description(string description)
  {
    _def.Description = description;
    return this;
  }

  /// <summary>
  /// Configures base props.
  /// </summary>
  public PackageBuilder Props(Action<PropsBuilder> configure)
  {
    configure(new PropsBuilder(_def.Props));
    return this;
  }

  /// <summary>
  /// Configures base targets.
  /// </summary>
  public PackageBuilder Targets(Action<TargetsBuilder> configure)
  {
    configure(new TargetsBuilder(_def.Targets));
    return this;
  }

  /// <summary>
  /// Configures build/ props output.
  /// </summary>
  public PackageBuilder BuildProps(Action<PropsBuilder> configure)
  {
    _def.BuildProps ??= NewProject();
    configure(new PropsBuilder(_def.BuildProps));
    return this;
  }

  /// <summary>
  /// Configures build/ targets output.
  /// </summary>
  public PackageBuilder BuildTargets(Action<TargetsBuilder> configure)
  {
    _def.BuildTargets ??= NewProject();
    configure(new TargetsBuilder(_def.BuildTargets));
    return this;
  }

  /// <summary>
  /// Configures buildTransitive/ props output.
  /// </summary>
  public PackageBuilder BuildTransitiveProps(Action<PropsBuilder> configure)
  {
    _def.BuildTransitiveProps ??= NewProject();
    configure(new PropsBuilder(_def.BuildTransitiveProps));
    return this;
  }

  /// <summary>
  /// Configures buildTransitive/ targets output.
  /// </summary>
  public PackageBuilder BuildTransitiveTargets(Action<TargetsBuilder> configure)
  {
    _def.BuildTransitiveTargets ??= NewProject();
    configure(new TargetsBuilder(_def.BuildTransitiveTargets));
    return this;
  }

  /// <summary>
  /// Configures Sdk props output.
  /// </summary>
  public PackageBuilder SdkProps(Action<PropsBuilder> configure)
  {
    _def.SdkProps ??= NewProject();
    configure(new PropsBuilder(_def.SdkProps));
    return this;
  }

  /// <summary>
  /// Configures Sdk targets output.
  /// </summary>
  public PackageBuilder SdkTargets(Action<TargetsBuilder> configure)
  {
    _def.SdkTargets ??= NewProject();
    configure(new TargetsBuilder(_def.SdkTargets));
    return this;
  }

  /// <summary>
  /// Configures packaging options.
  /// </summary>
  public PackageBuilder Pack(Action<PackagePackagingOptions> configure)
  {
    configure(_def.Packaging);
    return this;
  }

  /// <summary>
  /// Builds the final package definition.
  /// </summary>
  public PackageDefinition Build() => _def;

  private static MsBuildProject NewProject()
    => new() { Label = "Generated by JD.MSBuild.Fluent" };
}

/// <summary>
/// Fluent builder for props (property/item/import/choose) files.
/// </summary>
public sealed class PropsBuilder
{
  private readonly MsBuildProject _project;

  /// <summary>
  /// Creates a props builder for an existing project.
  /// </summary>
  public static PropsBuilder For(MsBuildProject project) => new(project);

  internal PropsBuilder(MsBuildProject project) => _project = project;

  /// <summary>
  /// Adds an Import to the project.
  /// </summary>
  public PropsBuilder Import(string project, string? condition = null, string? sdk = null)
  {
    var import = new MsBuildImport { Project = project, Condition = condition, Sdk = sdk };
    _project.Imports.Add(import);
    _project.Elements.Add(import);
    return this;
  }

  /// <summary>
  /// Adds a project-level comment.
  /// </summary>
  public PropsBuilder Comment(string text)
  {
    _project.Elements.Add(new MsBuildComment { Text = text });
    return this;
  }

  /// <summary>
  /// Adds a property to the last property group or creates one if needed.
  /// </summary>
  public PropsBuilder Property(string name, string value, string? condition = null)
  {
    var pg = _project.PropertyGroups.Count == 0 ? AddPropertyGroup() : _project.PropertyGroups[^1];
    AddProperty(pg, new MsBuildProperty { Name = name, Value = value, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed property to the last property group or creates one if needed.
  /// </summary>
  public PropsBuilder Property(IMsBuildPropertyName name, string value, string? condition = null)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return Property(name.Name, value, condition);
  }

  /// <summary>
  /// Adds a strongly-typed property to the last property group or creates one if needed.
  /// </summary>
  public PropsBuilder Property<TProperty>(string value, string? condition = null)
    where TProperty : IMsBuildPropertyName, new()
    => Property(new TProperty(), value, condition);

  /// <summary>
  /// Adds a new property group.
  /// </summary>
  public PropsBuilder PropertyGroup(string? condition, Action<PropsGroupBuilder> configure, string? label = null)
  {
    var pg = AddPropertyGroup(condition, label);
    configure(new PropsGroupBuilder(pg));
    return this;
  }

  /// <summary>
  /// Adds an item to the last item group or creates one if needed.
  /// </summary>
  public PropsBuilder Item(string itemType, MsBuildItemOperation op, string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
  {
    var ig = _project.ItemGroups.Count == 0 ? AddItemGroup() : _project.ItemGroups[^1];
    var item = new MsBuildItem { ItemType = itemType, Operation = op, Spec = spec, Condition = condition, Exclude = exclude };
    configure?.Invoke(new ItemBuilder(item));
    AddItem(ig, item);
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed item to the last item group or creates one if needed.
  /// </summary>
  public PropsBuilder Item(IMsBuildItemTypeName itemType, MsBuildItemOperation op, string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
  {
    if (itemType is null) throw new ArgumentNullException(nameof(itemType));
    return Item(itemType.Name, op, spec, configure, condition, exclude);
  }

  /// <summary>
  /// Adds a strongly-typed item to the last item group or creates one if needed.
  /// </summary>
  public PropsBuilder Item<TItem>(MsBuildItemOperation op, string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
    where TItem : IMsBuildItemTypeName, new()
    => Item(new TItem(), op, spec, configure, condition, exclude);

  /// <summary>
  /// Adds a new item group.
  /// </summary>
  public PropsBuilder ItemGroup(string? condition, Action<ItemGroupBuilder> configure, string? label = null)
  {
    var ig = AddItemGroup(condition, label);
    configure(new ItemGroupBuilder(ig));
    return this;
  }

  /// <summary>
  /// Adds a Choose element.
  /// </summary>
  public PropsBuilder Choose(Action<ChooseBuilder> configure)
  {
    var choose = new MsBuildChoose();
    configure(new ChooseBuilder(choose));
    _project.Chooses.Add(choose);
    _project.Elements.Add(choose);
    return this;
  }

  private MsBuildPropertyGroup AddPropertyGroup(string? condition = null, string? label = null)
  {
    var pg = new MsBuildPropertyGroup { Condition = condition, Label = label };
    _project.PropertyGroups.Add(pg);
    _project.Elements.Add(pg);
    return pg;
  }

  private MsBuildItemGroup AddItemGroup(string? condition = null, string? label = null)
  {
    var ig = new MsBuildItemGroup { Condition = condition, Label = label };
    _project.ItemGroups.Add(ig);
    _project.Elements.Add(ig);
    return ig;
  }

  internal static void AddProperty(MsBuildPropertyGroup group, MsBuildProperty property)
  {
    group.Properties.Add(property);
    group.Entries.Add(property);
  }

  internal static void AddItem(MsBuildItemGroup group, MsBuildItem item)
  {
    group.Items.Add(item);
    group.Entries.Add(item);
  }
}

/// <summary>
/// Fluent builder for a PropertyGroup.
/// </summary>
public sealed class PropsGroupBuilder
{
  private readonly MsBuildPropertyGroup _group;
  internal PropsGroupBuilder(MsBuildPropertyGroup group) => _group = group;

  /// <summary>
  /// Adds a property to the group.
  /// </summary>
  public PropsGroupBuilder Property(string name, string value, string? condition = null)
  {
    PropsBuilder.AddProperty(_group, new MsBuildProperty { Name = name, Value = value, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed property to the group.
  /// </summary>
  public PropsGroupBuilder Property(IMsBuildPropertyName name, string value, string? condition = null)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return Property(name.Name, value, condition);
  }

  /// <summary>
  /// Adds a strongly-typed property to the group.
  /// </summary>
  public PropsGroupBuilder Property<TProperty>(string value, string? condition = null)
    where TProperty : IMsBuildPropertyName, new()
    => Property(new TProperty(), value, condition);

  /// <summary>
  /// Adds a comment to the group.
  /// </summary>
  public PropsGroupBuilder Comment(string text)
  {
    _group.Entries.Add(new MsBuildComment { Text = text });
    return this;
  }
}

/// <summary>
/// Fluent builder for an ItemGroup.
/// </summary>
public sealed class ItemGroupBuilder
{
  private readonly MsBuildItemGroup _group;
  internal ItemGroupBuilder(MsBuildItemGroup group) => _group = group;

  /// <summary>
  /// Adds an Include item.
  /// </summary>
  public ItemGroupBuilder Include(string itemType, string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
  {
    var item = new MsBuildItem { ItemType = itemType, Operation = MsBuildItemOperation.Include, Spec = spec, Condition = condition, Exclude = exclude };
    configure?.Invoke(new ItemBuilder(item));
    PropsBuilder.AddItem(_group, item);
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed Include item.
  /// </summary>
  public ItemGroupBuilder Include(IMsBuildItemTypeName itemType, string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
  {
    if (itemType is null) throw new ArgumentNullException(nameof(itemType));
    return Include(itemType.Name, spec, configure, condition, exclude);
  }

  /// <summary>
  /// Adds a strongly-typed Include item.
  /// </summary>
  public ItemGroupBuilder Include<TItem>(string spec, Action<ItemBuilder>? configure = null, string? condition = null, string? exclude = null)
    where TItem : IMsBuildItemTypeName, new()
    => Include(new TItem(), spec, configure, condition, exclude);

  /// <summary>
  /// Adds a Remove item.
  /// </summary>
  public ItemGroupBuilder Remove(string itemType, string spec, string? condition = null)
  {
    PropsBuilder.AddItem(_group, new MsBuildItem { ItemType = itemType, Operation = MsBuildItemOperation.Remove, Spec = spec, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed Remove item.
  /// </summary>
  public ItemGroupBuilder Remove(IMsBuildItemTypeName itemType, string spec, string? condition = null)
  {
    if (itemType is null) throw new ArgumentNullException(nameof(itemType));
    return Remove(itemType.Name, spec, condition);
  }

  /// <summary>
  /// Adds a strongly-typed Remove item.
  /// </summary>
  public ItemGroupBuilder Remove<TItem>(string spec, string? condition = null)
    where TItem : IMsBuildItemTypeName, new()
    => Remove(new TItem(), spec, condition);

  /// <summary>
  /// Adds an Update item.
  /// </summary>
  public ItemGroupBuilder Update(string itemType, string spec, Action<ItemBuilder> configure, string? condition = null)
  {
    var item = new MsBuildItem { ItemType = itemType, Operation = MsBuildItemOperation.Update, Spec = spec, Condition = condition };
    configure(new ItemBuilder(item));
    PropsBuilder.AddItem(_group, item);
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed Update item.
  /// </summary>
  public ItemGroupBuilder Update(IMsBuildItemTypeName itemType, string spec, Action<ItemBuilder> configure, string? condition = null)
  {
    if (itemType is null) throw new ArgumentNullException(nameof(itemType));
    return Update(itemType.Name, spec, configure, condition);
  }

  /// <summary>
  /// Adds a strongly-typed Update item.
  /// </summary>
  public ItemGroupBuilder Update<TItem>(string spec, Action<ItemBuilder> configure, string? condition = null)
    where TItem : IMsBuildItemTypeName, new()
    => Update(new TItem(), spec, configure, condition);

  /// <summary>
  /// Adds a comment to the group.
  /// </summary>
  public ItemGroupBuilder Comment(string text)
  {
    _group.Entries.Add(new MsBuildComment { Text = text });
    return this;
  }
}

/// <summary>
/// Fluent builder for an individual item.
/// </summary>
public sealed class ItemBuilder
{
  private readonly MsBuildItem _item;
  internal ItemBuilder(MsBuildItem item) => _item = item;

  /// <summary>
  /// Sets the Exclude attribute for the item.
  /// </summary>
  public ItemBuilder Exclude(string spec)
  {
    _item.Exclude = spec;
    return this;
  }

  /// <summary>
  /// Adds metadata as a child element.
  /// </summary>
  public ItemBuilder Meta(string name, string value)
  {
    _item.Metadata[name] = value;
    return this;
  }

  /// <summary>
  /// Adds strongly-typed metadata as a child element.
  /// </summary>
  public ItemBuilder Meta(IMsBuildMetadataName name, string value)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return Meta(name.Name, value);
  }

  /// <summary>
  /// Adds strongly-typed metadata as a child element.
  /// </summary>
  public ItemBuilder Meta<TMetadata>(string value)
    where TMetadata : IMsBuildMetadataName, new()
    => Meta(new TMetadata(), value);

  /// <summary>
  /// Adds metadata as an attribute.
  /// </summary>
  public ItemBuilder MetaAttribute(string name, string value)
  {
    _item.MetadataAttributes[name] = value;
    return this;
  }

  /// <summary>
  /// Adds strongly-typed metadata as an attribute.
  /// </summary>
  public ItemBuilder MetaAttribute(IMsBuildMetadataName name, string value)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return MetaAttribute(name.Name, value);
  }

  /// <summary>
  /// Adds strongly-typed metadata as an attribute.
  /// </summary>
  public ItemBuilder MetaAttribute<TMetadata>(string value)
    where TMetadata : IMsBuildMetadataName, new()
    => MetaAttribute(new TMetadata(), value);
}

/// <summary>
/// Fluent builder for a Choose element.
/// </summary>
public sealed class ChooseBuilder
{
  private readonly MsBuildChoose _choose;
  internal ChooseBuilder(MsBuildChoose choose) => _choose = choose;

  /// <summary>
  /// Adds a When clause with the specified condition.
  /// </summary>
  public ChooseBuilder When(string condition, Action<PropsBuilder> configure)
  {
    var when = new MsBuildWhen { Condition = condition };
    var tempProject = new MsBuildProject();
    configure(new PropsBuilder(tempProject));
    when.PropertyGroups.AddRange(tempProject.PropertyGroups);
    when.ItemGroups.AddRange(tempProject.ItemGroups);
    _choose.Whens.Add(when);
    return this;
  }

  /// <summary>
  /// Adds an Otherwise clause.
  /// </summary>
  public ChooseBuilder Otherwise(Action<PropsBuilder> configure)
  {
    var other = new MsBuildOtherwise();
    var tempProject = new MsBuildProject();
    configure(new PropsBuilder(tempProject));
    other.PropertyGroups.AddRange(tempProject.PropertyGroups);
    other.ItemGroups.AddRange(tempProject.ItemGroups);
    _choose.Otherwise = other;
    return this;
  }
}

/// <summary>
/// Fluent builder for targets files (UsingTask/Target/etc.).
/// </summary>
public sealed class TargetsBuilder
{
  private readonly MsBuildProject _project;
  internal TargetsBuilder(MsBuildProject project) => _project = project;

  /// <summary>
  /// Creates a targets builder for an existing project.
  /// </summary>
  public static TargetsBuilder For(MsBuildProject project) => new(project);

  /// <summary>
  /// Adds a UsingTask declaration.
  /// </summary>
  public TargetsBuilder UsingTask(string taskName, string? assemblyFile, string? condition = null, string? assemblyName = null, string? taskFactory = null)
  {
    var ut = new MsBuildUsingTask
    {
      TaskName = taskName,
      AssemblyFile = assemblyFile,
      AssemblyName = assemblyName,
      TaskFactory = taskFactory,
      Condition = condition
    };
    _project.UsingTasks.Add(ut);
    _project.Elements.Add(ut);
    return this;
  }

  /// <summary>
  /// Adds a UsingTask declaration from a task reference.
  /// </summary>
  public TargetsBuilder UsingTask(MsBuildTaskReference task, string? condition = null)
    => UsingTask(task.Name, task.AssemblyFile, condition, task.AssemblyName, task.TaskFactory);

  /// <summary>
  /// Adds a UsingTask declaration from a CLR task type.
  /// </summary>
  public TargetsBuilder UsingTask<TTask>(string? assemblyFile = null, string? condition = null, string? assemblyName = null, string? taskFactory = null, MsBuildTaskNameStyle nameStyle = MsBuildTaskNameStyle.FullName)
    => UsingTask(MsBuildTaskReference.FromType<TTask>(nameStyle, assemblyFile, assemblyName, taskFactory), condition);

  /// <summary>
  /// Adds a project-level comment.
  /// </summary>
  public TargetsBuilder Comment(string text)
  {
    _project.Elements.Add(new MsBuildComment { Text = text });
    return this;
  }

  /// <summary>
  /// Adds an Import to the project.
  /// </summary>
  public TargetsBuilder Import(string project, string? condition = null, string? sdk = null)
  {
    var import = new MsBuildImport { Project = project, Condition = condition, Sdk = sdk };
    _project.Imports.Add(import);
    _project.Elements.Add(import);
    return this;
  }

  /// <summary>
  /// Adds a Target.
  /// </summary>
  public TargetsBuilder Target(string name, Action<TargetBuilder> configure)
  {
    var t = new MsBuildTarget { Name = name };
    configure(new TargetBuilder(t));
    _project.Targets.Add(t);
    _project.Elements.Add(t);
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed Target.
  /// </summary>
  public TargetsBuilder Target(IMsBuildTargetName name, Action<TargetBuilder> configure)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return Target(name.Name, configure);
  }

  /// <summary>
  /// Adds a strongly-typed Target.
  /// </summary>
  public TargetsBuilder Target<TTarget>(Action<TargetBuilder> configure)
    where TTarget : IMsBuildTargetName, new()
    => Target(new TTarget(), configure);

  /// <summary>
  /// Adds a PropertyGroup at the project level.
  /// </summary>
  public TargetsBuilder PropertyGroup(string? condition, Action<PropsGroupBuilder> configure, string? label = null)
  {
    var pg = new MsBuildPropertyGroup { Condition = condition, Label = label };
    configure(new PropsGroupBuilder(pg));
    _project.PropertyGroups.Add(pg);
    _project.Elements.Add(pg);
    return this;
  }

  /// <summary>
  /// Adds an ItemGroup at the project level.
  /// </summary>
  public TargetsBuilder ItemGroup(string? condition, Action<ItemGroupBuilder> configure, string? label = null)
  {
    var ig = new MsBuildItemGroup { Condition = condition, Label = label };
    configure(new ItemGroupBuilder(ig));
    _project.ItemGroups.Add(ig);
    _project.Elements.Add(ig);
    return this;
  }
}

/// <summary>
/// Fluent builder for a Target element.
/// </summary>
public sealed class TargetBuilder
{
  private readonly MsBuildTarget _target;
  internal TargetBuilder(MsBuildTarget target) => _target = target;

  /// <summary>
  /// Sets the target Condition.
  /// </summary>
  public TargetBuilder Condition(string condition) { _target.Condition = condition; return this; }
  /// <summary>
  /// Sets the BeforeTargets attribute.
  /// </summary>
  public TargetBuilder BeforeTargets(string before) { _target.BeforeTargets = before; return this; }
  /// <summary>
  /// Sets the BeforeTargets attribute using strongly-typed targets.
  /// </summary>
  public TargetBuilder BeforeTargets(params IMsBuildTargetName[] targets) { _target.BeforeTargets = JoinTargets(targets); return this; }
  /// <summary>
  /// Sets the AfterTargets attribute.
  /// </summary>
  public TargetBuilder AfterTargets(string after) { _target.AfterTargets = after; return this; }
  /// <summary>
  /// Sets the AfterTargets attribute using strongly-typed targets.
  /// </summary>
  public TargetBuilder AfterTargets(params IMsBuildTargetName[] targets) { _target.AfterTargets = JoinTargets(targets); return this; }
  /// <summary>
  /// Sets the DependsOnTargets attribute.
  /// </summary>
  public TargetBuilder DependsOnTargets(string depends) { _target.DependsOnTargets = depends; return this; }
  /// <summary>
  /// Sets the DependsOnTargets attribute using strongly-typed targets.
  /// </summary>
  public TargetBuilder DependsOnTargets(params IMsBuildTargetName[] targets) { _target.DependsOnTargets = JoinTargets(targets); return this; }
  /// <summary>
  /// Sets the Inputs attribute.
  /// </summary>
  public TargetBuilder Inputs(string inputs) { _target.Inputs = inputs; return this; }
  /// <summary>
  /// Sets the Outputs attribute.
  /// </summary>
  public TargetBuilder Outputs(string outputs) { _target.Outputs = outputs; return this; }
  /// <summary>
  /// Sets the Label attribute.
  /// </summary>
  public TargetBuilder Label(string label) { _target.Label = label; return this; }

  /// <summary>
  /// Adds a Message task to the target.
  /// </summary>
  public TargetBuilder Message(string text, string importance = "High", string? condition = null)
  {
    _target.Elements.Add(new MsBuildMessageStep { Text = text, Importance = importance, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds an Exec task to the target.
  /// </summary>
  public TargetBuilder Exec(string command, string? workingDirectory = null, string? condition = null)
  {
    _target.Elements.Add(new MsBuildExecStep { Command = command, WorkingDirectory = workingDirectory, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds an arbitrary task to the target.
  /// </summary>
  public TargetBuilder Task(string taskName, Action<TaskInvocationBuilder> configure, string? condition = null)
  {
    var step = new MsBuildTaskStep { TaskName = taskName, Condition = condition };
    configure(new TaskInvocationBuilder(step));
    _target.Elements.Add(step);
    return this;
  }

  /// <summary>
  /// Adds an arbitrary task to the target from a strongly-typed task name.
  /// </summary>
  public TargetBuilder Task(IMsBuildTaskName taskName, Action<TaskInvocationBuilder> configure, string? condition = null)
  {
    if (taskName is null) throw new ArgumentNullException(nameof(taskName));
    return Task(taskName.Name, configure, condition);
  }

  /// <summary>
  /// Adds an arbitrary task to the target from a task reference.
  /// </summary>
  public TargetBuilder Task(MsBuildTaskReference task, Action<TaskInvocationBuilder> configure, string? condition = null)
    => Task(task.Name, configure, condition);

  /// <summary>
  /// Adds an arbitrary task to the target from a CLR task type.
  /// </summary>
  public TargetBuilder Task<TTask>(Action<TaskInvocationBuilder> configure, string? condition = null, MsBuildTaskNameStyle nameStyle = MsBuildTaskNameStyle.FullName)
    => Task(MsBuildTaskReference.FromType<TTask>(nameStyle), configure, condition);

  /// <summary>
  /// Adds an Error task to the target.
  /// </summary>
  public TargetBuilder Error(string text, string? condition = null, string? code = null)
  {
    _target.Elements.Add(new MsBuildErrorStep { Text = text, Code = code, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds a Warning task to the target.
  /// </summary>
  public TargetBuilder Warning(string text, string? condition = null, string? code = null)
  {
    _target.Elements.Add(new MsBuildWarningStep { Text = text, Code = code, Condition = condition });
    return this;
  }

  /// <summary>
  /// Adds a comment to the target.
  /// </summary>
  public TargetBuilder Comment(string text)
  {
    _target.Elements.Add(new MsBuildTargetComment { Text = text });
    return this;
  }

  /// <summary>
  /// Adds a PropertyGroup inside the target.
  /// </summary>
  public TargetBuilder PropertyGroup(string? condition, Action<PropsGroupBuilder> configure, string? label = null)
  {
    var group = new MsBuildPropertyGroup { Condition = condition, Label = label };
    configure(new PropsGroupBuilder(group));
    _target.Elements.Add(new MsBuildPropertyGroupElement(group));
    return this;
  }

  /// <summary>
  /// Adds an ItemGroup inside the target.
  /// </summary>
  public TargetBuilder ItemGroup(string? condition, Action<ItemGroupBuilder> configure, string? label = null)
  {
    var group = new MsBuildItemGroup { Condition = condition, Label = label };
    configure(new ItemGroupBuilder(group));
    _target.Elements.Add(new MsBuildItemGroupElement(group));
    return this;
  }

  private static string JoinTargets(IMsBuildTargetName[] targets)
  {
    if (targets is null) throw new ArgumentNullException(nameof(targets));
    return string.Join(";", targets.Where(t => t is not null).Select(t => t.Name));
  }
}

/// <summary>
/// Fluent builder for task parameters and outputs.
/// </summary>
public sealed class TaskInvocationBuilder
{
  private readonly MsBuildTaskStep _step;
  internal TaskInvocationBuilder(MsBuildTaskStep step) => _step = step;

  /// <summary>
  /// Adds a task parameter.
  /// </summary>
  public TaskInvocationBuilder Param(string name, string value)
  {
    _step.Parameters[name] = value;
    return this;
  }

  /// <summary>
  /// Adds a strongly-typed task parameter.
  /// </summary>
  public TaskInvocationBuilder Param(IMsBuildTaskParameterName name, string value)
  {
    if (name is null) throw new ArgumentNullException(nameof(name));
    return Param(name.Name, value);
  }

  /// <summary>
  /// Adds a strongly-typed task parameter.
  /// </summary>
  public TaskInvocationBuilder Param<TParam>(string value)
    where TParam : IMsBuildTaskParameterName, new()
    => Param(new TParam(), value);

  /// <summary>
  /// Adds a task Output mapping to a property.
  /// </summary>
  public TaskInvocationBuilder OutputProperty(string taskParameter, string propertyName, string? condition = null)
  {
    _step.Outputs.Add(new MsBuildTaskOutput
    {
      TaskParameter = taskParameter,
      PropertyName = propertyName,
      Condition = condition
    });
    return this;
  }

  /// <summary>
  /// Adds a task Output mapping to a strongly-typed property.
  /// </summary>
  public TaskInvocationBuilder OutputProperty(IMsBuildTaskParameterName taskParameter, IMsBuildPropertyName propertyName, string? condition = null)
  {
    if (taskParameter is null) throw new ArgumentNullException(nameof(taskParameter));
    if (propertyName is null) throw new ArgumentNullException(nameof(propertyName));
    return OutputProperty(taskParameter.Name, propertyName.Name, condition);
  }

  /// <summary>
  /// Adds a task Output mapping to a strongly-typed property.
  /// </summary>
  public TaskInvocationBuilder OutputProperty<TParam, TProperty>(string? condition = null)
    where TParam : IMsBuildTaskParameterName, new()
    where TProperty : IMsBuildPropertyName, new()
    => OutputProperty(new TParam(), new TProperty(), condition);

  /// <summary>
  /// Adds a task Output mapping to an item.
  /// </summary>
  public TaskInvocationBuilder OutputItem(string taskParameter, string itemName, string? condition = null)
  {
    _step.Outputs.Add(new MsBuildTaskOutput
    {
      TaskParameter = taskParameter,
      ItemName = itemName,
      Condition = condition
    });
    return this;
  }

  /// <summary>
  /// Adds a task Output mapping to a strongly-typed item.
  /// </summary>
  public TaskInvocationBuilder OutputItem(IMsBuildTaskParameterName taskParameter, IMsBuildItemTypeName itemName, string? condition = null)
  {
    if (taskParameter is null) throw new ArgumentNullException(nameof(taskParameter));
    if (itemName is null) throw new ArgumentNullException(nameof(itemName));
    return OutputItem(taskParameter.Name, itemName.Name, condition);
  }

  /// <summary>
  /// Adds a task Output mapping to a strongly-typed item.
  /// </summary>
  public TaskInvocationBuilder OutputItem<TParam, TItem>(string? condition = null)
    where TParam : IMsBuildTaskParameterName, new()
    where TItem : IMsBuildItemTypeName, new()
    => OutputItem(new TParam(), new TItem(), condition);
}
