using JD.MSBuild.Fluent.IR;
using JD.MSBuild.Fluent.Packaging;

namespace JD.MSBuild.Fluent;

/// <summary>
/// Top-level definition for a package (targets package or MSBuild SDK package).
/// </summary>
public sealed class PackageDefinition
{
  /// <summary>
  /// NuGet package ID.
  /// </summary>
  public required string Id { get; init; }
  /// <summary>
  /// Optional description for package metadata.
  /// </summary>
  public string? Description { get; set; }

  /// <summary>
  /// Props are evaluation-time constructs (properties, items, imports). Avoid Targets here.
  /// </summary>
  public MsBuildProject Props { get; } = new() { Label = "Generated by JD.MSBuild.Fluent" };

  /// <summary>
  /// Targets are execution-time constructs (UsingTask, Target, tasks/exec, etc.).
  /// </summary>
  public MsBuildProject Targets { get; } = new() { Label = "Generated by JD.MSBuild.Fluent" };

  /// <summary>
  /// Optional build/.props project.
  /// </summary>
  public MsBuildProject? BuildProps { get; set; }
  /// <summary>
  /// Optional build/.targets project.
  /// </summary>
  public MsBuildProject? BuildTargets { get; set; }
  /// <summary>
  /// Optional buildTransitive/.props project.
  /// </summary>
  public MsBuildProject? BuildTransitiveProps { get; set; }
  /// <summary>
  /// Optional buildTransitive/.targets project.
  /// </summary>
  public MsBuildProject? BuildTransitiveTargets { get; set; }
  /// <summary>
  /// Optional Sdk/Sdk.props project.
  /// </summary>
  public MsBuildProject? SdkProps { get; set; }
  /// <summary>
  /// Optional Sdk/Sdk.targets project.
  /// </summary>
  public MsBuildProject? SdkTargets { get; set; }

  /// <summary>
  /// Packaging options controlling emitted assets.
  /// </summary>
  public PackagePackagingOptions Packaging { get; set; } = new();

  /// <summary>
  /// Returns the build props project, falling back to <see cref="Props"/>.
  /// </summary>
  public MsBuildProject GetBuildProps() => BuildProps ?? Props;
  /// <summary>
  /// Returns the build targets project, falling back to <see cref="Targets"/>.
  /// </summary>
  public MsBuildProject GetBuildTargets() => BuildTargets ?? Targets;
  /// <summary>
  /// Returns the buildTransitive props project, falling back to <see cref="Props"/>.
  /// </summary>
  public MsBuildProject GetBuildTransitiveProps() => BuildTransitiveProps ?? Props;
  /// <summary>
  /// Returns the buildTransitive targets project, falling back to <see cref="Targets"/>.
  /// </summary>
  public MsBuildProject GetBuildTransitiveTargets() => BuildTransitiveTargets ?? Targets;
  /// <summary>
  /// Returns the SDK props project, falling back to <see cref="Props"/>.
  /// </summary>
  public MsBuildProject GetSdkProps() => SdkProps ?? Props;
  /// <summary>
  /// Returns the SDK targets project, falling back to <see cref="Targets"/>.
  /// </summary>
  public MsBuildProject GetSdkTargets() => SdkTargets ?? Targets;
}
